#!/usr/bin/env bash

if [ -z "${PHP_VERSION}" ]; then
  PHP_VERSION='7.4'
fi

. /vagrant/vagrant-config/environment.sh

debconf-set-selections <<<"mysql-server mysql-server/root_password password ${MYSQL_ROOT_PASSWORD}"
debconf-set-selections <<<"mysql-server mysql-server/root_password_again password ${MYSQL_ROOT_PASSWORD}"

sudo timedatectl set-timezone America/Sao_Paulo

add-apt-repository -y ppa:ondrej/php && add-apt-repository -y ppa:ondrej/nginx-mainline

apt-get update -y --allow-downgrades \
  && apt autoremove -y --allow-downgrades \
  && apt-get upgrade -y --allow-downgrades \
  && apt-get dist-upgrade -y --allow-downgrades

apt-get install -y nginx \
  "php${PHP_VERSION}" \
  "php${PHP_VERSION}-fpm" \
  "php${PHP_VERSION}-gd" \
  "php${PHP_VERSION}-mysql" \
  "php${PHP_VERSION}-cgi" \
  "php${PHP_VERSION}-cli" \
  "php${PHP_VERSION}-curl" \
  "php${PHP_VERSION}-mbstring" \
  "php${PHP_VERSION}-xdebug" \
  ffmpeg \
  vim \
  git-core \
  mysql-server \
  mysql-client \
  curl \
  tmux \
  zip \
  unzip

echo "**** ADD BYOBU CONFIG"
. /vagrant/vagrant-wordpress/configs/byobu.sh

echo "**** MOVING NGINX CONFIG FILES INTO PLACE…"
. /vagrant/vagrant-wordpress/nginx/nginx.sh

echo "**** MYSQL CONFIG…"
. /vagrant/vagrant-wordpress/mysql/mysql.sh

echo "**** SET PHP TO ${PHP_VERSION} AND COPY CONFIG FILES"
. /vagrant/vagrant-wordpress/php/php.sh

echo "STARTING SERVICES…"
service nginx restart && service "php${PHP_VERSION}-fpm" restart && service mysql restart

# WP-CLI
. /vagrant/vagrant-wordpress/wordpress/wp-cli.sh

# Create database
. /vagrant/vagrant-wordpress/mysql/create_database.sh

# Install WP
. /vagrant/vagrant-wordpress/wordpress/install.sh

# Import database
. /vagrant/vagrant-wordpress/mysql/import_database.sh

# Install Composer
. /vagrant/vagrant-wordpress/composer/install.sh

# Initialization
. /vagrant/vagrant-wordpress/wordpress/initialization.sh
